name: cs7643-a1
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - ta